LOCAL_PATH:=$(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := PotatoFries

ifdef TARGET_2ND_ARCH
LOCAL_SRC_FILES := $(LOCAL_MODULE)-arm64.apk
else
LOCAL_SRC_FILES := $(LOCAL_MODULE)-arm.apk
endif

LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)
