ifeq($(PRODUCT_DEVICE), bacon)
    POTATO_MANTAINER := AgentFabulous
else ifeq($(PRODUCT_DEVICE), berkeley)
    POTATO_MANTAINER := DavidSn
else ifeq($(PRODUCT_DEVICE), beryllium)
    POTATO_MANTAINER := AgentFabulous
else ifeq($(PRODUCT_DEVICE), cheeseburger)
    POTATO_MANTAINER := georgemath24
else ifeq($(PRODUCT_DEVICE), chiron)
    POTATO_MANTAINER := HrX
else ifeq($(PRODUCT_DEVICE), dipper)
    POTATO_MANTAINER := Argraur
else ifeq($(PRODUCT_DEVICE), enchilada)
    POTATO_MANTAINER := SamriddhaBasu
else ifeq($(PRODUCT_DEVICE), fajita)
    POTATO_MANTAINER := Ujwal
else ifeq($(PRODUCT_DEVICE), kenzo)
    POTATO_MANTAINER := AbsarRahman
else ifeq($(PRODUCT_DEVICE), mido)
    POTATO_MANTAINER := Rahul
else ifeq($(PRODUCT_DEVICE), oneplus2)
    POTATO_MANTAINER := ShreyanshLodha
else ifeq($(PRODUCT_DEVICE), oneplus3)
    POTATO_MANTAINER := JagravNaik
else ifeq($(PRODUCT_DEVICE), onyx)
    POTATO_MANTAINER := kushagra57
else ifeq($(PRODUCT_DEVICE), potter)
    POTATO_MANTAINER := AshWINRC
else ifeq($(PRODUCT_DEVICE), sanders)
    POTATO_MANTAINER := DybyajyotiSamal
else ifeq($(PRODUCT_DEVICE), whyred)
    POTATO_MANTAINER := RajJadeja
else ifeq($(PRODUCT_DEVICE), X00T)
    POTATO_MANTAINER := AkashKhatri
endif
